### ISSUE TITLE
Error on windows 7/8

### ISSUE THREAD

**Issue by poslavsky** [alexfedoseev/universal-basics#1]
When run "npm start" on Windows 7/8 - error.
http://ipic.su/img/img7/fs/MINGW32__C_DEV_universal-basics2015-08-0920.1439194237.jpg

**Comment by alex35mil** [comment]
Sorry but I don't have any Windows to debug this one. And I can't even guess what's wrong, because I've never used Win for dev.

My advices:
1. Ask for help on StackOverflow (or similar).
2. Get OS ending with X (and it's should NOT be Windows Ten).

**Comment by poslavsky** [comment]
Unfortunately there is no time to try to make the correct version for Windows.
But maybe, these links will help you to do windows-friendly app in the future.
https://github.com/erikras/react-redux-universal-hot-example/pull/21
https://toster.ru/q/240616
