### ISSUE TITLE
Gulp start:dev error on npm start

### ISSUE THREAD

**Issue by kelseypedersen** [alexfedoseev/universal-basics#2]
Has anyone else seen this error? Happened on npm start. 

"18 error universal-basics@0.0.1 start: `gulp start:dev`
18 error Exit status 1
19 error Failed at the universal-basics@0.0.1 start script 'gulp start:dev'.
19 error This is most likely a problem with the universal-basics package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     gulp start:dev
19 error You can get their info via:
19 error     npm owner ls universal-basics"

**Comment by sarovin** [comment]
I have the same error...

**Comment by alex35mil** [comment]
@kpedersen00 Just pushed fixes, please pull latest and reinstall deps.
